view attendance
X-workzDev01/Xworkz-Api pull request #199
Opened 2024-02-06 05:16 UTC by X-workzDev01

2024-02-06 10:04 UTC, X-workzDev01 commented on src/main/java/com/xworkz/dream/repository/AttendanceRepository.java
> +	public List<List<Object>> getNamesAndCourseName(String spreadsheetId,String range, String value) throws IOException;
remove  all public

2024-02-06 10:04 UTC, X-workzDev01 commented on src/main/java/com/xworkz/dream/repository/AttendanceRepositoryImpl.java
> +		log.info("Reading names and courseName from sheet for spreadsheetId: {}", spreadsheetId);
remove throws

2024-02-06 10:04 UTC, X-workzDev01 commented on src/main/java/com/xworkz/dream/service/AttendanceService.java
remove public and throws

2024-02-07 10:03 UTC, xworkzodc requested changes

2024-02-07 10:03 UTC, xworkzodc commented on src/main/java/com/xworkz/dream/repository/AttendanceRepositoryImpl.java
> +			sheetsService.spreadsheets().values().append(sheetId, attendanceRange, body).setValueInputOption("USER_ENTERED")
Use constant

2024-02-07 11:10 UTC, merged